#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["flower-power-2/flower-power-2.csproj", "flower-power-2/"]
RUN dotnet restore "flower-power-2/flower-power-2.csproj"
COPY . .
WORKDIR "/src/flower-power-2"
RUN dotnet build "flower-power-2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "flower-power-2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "flower-power-2.dll"]
